/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/zhongjiawei/Desktop/hard-learn/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5d8a074e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d8a074e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7e412323",
    path: "/base-build/vite%E7%9B%B8%E5%85%B3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e412323").then(next)
    },
  },
  {
    path: "/base-build/vite相关.html",
    redirect: "/base-build/vite%E7%9B%B8%E5%85%B3.html"
  },
  {
    path: "/base-build/vite相关.html",
    redirect: "/base-build/vite%E7%9B%B8%E5%85%B3.html"
  },
  {
    name: "v-7d3afeea",
    path: "/base-css/BFC.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d3afeea").then(next)
    },
  },
  {
    name: "v-55e43ed6",
    path: "/base-css/%E5%9E%82%E7%9B%B4%E6%B0%B4%E5%B9%B3%E5%B1%85%E4%B8%AD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55e43ed6").then(next)
    },
  },
  {
    path: "/base-css/垂直水平居中.html",
    redirect: "/base-css/%E5%9E%82%E7%9B%B4%E6%B0%B4%E5%B9%B3%E5%B1%85%E4%B8%AD.html"
  },
  {
    path: "/base-css/垂直水平居中.html",
    redirect: "/base-css/%E5%9E%82%E7%9B%B4%E6%B0%B4%E5%B9%B3%E5%B1%85%E4%B8%AD.html"
  },
  {
    name: "v-72013c9f",
    path: "/base-css/%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E6%A8%A1%E6%80%81%E6%A1%86%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72013c9f").then(next)
    },
  },
  {
    path: "/base-css/实现一个模态框组件.html",
    redirect: "/base-css/%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E6%A8%A1%E6%80%81%E6%A1%86%E7%BB%84%E4%BB%B6.html"
  },
  {
    path: "/base-css/实现一个模态框组件.html",
    redirect: "/base-css/%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E6%A8%A1%E6%80%81%E6%A1%86%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-7d4f4f99",
    path: "/base-css/%E7%A7%BB%E5%8A%A8%E7%AB%AF1px%E8%BE%B9%E6%A1%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d4f4f99").then(next)
    },
  },
  {
    path: "/base-css/移动端1px边框.html",
    redirect: "/base-css/%E7%A7%BB%E5%8A%A8%E7%AB%AF1px%E8%BE%B9%E6%A1%86.html"
  },
  {
    path: "/base-css/移动端1px边框.html",
    redirect: "/base-css/%E7%A7%BB%E5%8A%A8%E7%AB%AF1px%E8%BE%B9%E6%A1%86.html"
  },
  {
    name: "v-2133aeca",
    path: "/base-css/%E4%B8%80%E9%94%AE%E6%8D%A2%E8%82%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2133aeca").then(next)
    },
  },
  {
    path: "/base-css/一键换肤.html",
    redirect: "/base-css/%E4%B8%80%E9%94%AE%E6%8D%A2%E8%82%A4.html"
  },
  {
    path: "/base-css/一键换肤.html",
    redirect: "/base-css/%E4%B8%80%E9%94%AE%E6%8D%A2%E8%82%A4.html"
  },
  {
    name: "v-79c77efc",
    path: "/base-fe/Diff%E7%AE%97%E6%B3%95%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79c77efc").then(next)
    },
  },
  {
    path: "/base-fe/Diff算法实现原理.html",
    redirect: "/base-fe/Diff%E7%AE%97%E6%B3%95%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/base-fe/Diff算法实现原理.html",
    redirect: "/base-fe/Diff%E7%AE%97%E6%B3%95%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-11b92706",
    path: "/base-fe/Vuex%E5%92%8CPinia.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11b92706").then(next)
    },
  },
  {
    path: "/base-fe/Vuex和Pinia.html",
    redirect: "/base-fe/Vuex%E5%92%8CPinia.html"
  },
  {
    path: "/base-fe/Vuex和Pinia.html",
    redirect: "/base-fe/Vuex%E5%92%8CPinia.html"
  },
  {
    name: "v-4f810be7",
    path: "/base-css/%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8%E6%9C%89%E5%93%AA%E4%BA%9B%E5%A5%BD%E5%A4%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f810be7").then(next)
    },
  },
  {
    path: "/base-css/预处理器有哪些好处.html",
    redirect: "/base-css/%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8%E6%9C%89%E5%93%AA%E4%BA%9B%E5%A5%BD%E5%A4%84.html"
  },
  {
    path: "/base-css/预处理器有哪些好处.html",
    redirect: "/base-css/%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8%E6%9C%89%E5%93%AA%E4%BA%9B%E5%A5%BD%E5%A4%84.html"
  },
  {
    name: "v-02bd9432",
    path: "/base-fe/vue3%E5%92%8Cvue2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02bd9432").then(next)
    },
  },
  {
    path: "/base-fe/vue3和vue2.html",
    redirect: "/base-fe/vue3%E5%92%8Cvue2.html"
  },
  {
    path: "/base-fe/vue3和vue2.html",
    redirect: "/base-fe/vue3%E5%92%8Cvue2.html"
  },
  {
    name: "v-308514af",
    path: "/base-fe/%E6%8C%87%E4%BB%A4%E5%92%8C%E6%8F%92%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-308514af").then(next)
    },
  },
  {
    path: "/base-fe/指令和插件.html",
    redirect: "/base-fe/%E6%8C%87%E4%BB%A4%E5%92%8C%E6%8F%92%E4%BB%B6.html"
  },
  {
    path: "/base-fe/指令和插件.html",
    redirect: "/base-fe/%E6%8C%87%E4%BB%A4%E5%92%8C%E6%8F%92%E4%BB%B6.html"
  },
  {
    name: "v-148aa696",
    path: "/base-fe/vue%E8%B7%AF%E7%94%B1%E5%AE%88%E5%8D%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-148aa696").then(next)
    },
  },
  {
    path: "/base-fe/vue路由守卫.html",
    redirect: "/base-fe/vue%E8%B7%AF%E7%94%B1%E5%AE%88%E5%8D%AB.html"
  },
  {
    path: "/base-fe/vue路由守卫.html",
    redirect: "/base-fe/vue%E8%B7%AF%E7%94%B1%E5%AE%88%E5%8D%AB.html"
  },
  {
    name: "v-4de26aa8",
    path: "/base-fe/vue3%E7%9B%B8%E5%85%B3%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4de26aa8").then(next)
    },
  },
  {
    path: "/base-fe/vue3相关总结.html",
    redirect: "/base-fe/vue3%E7%9B%B8%E5%85%B3%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/base-fe/vue3相关总结.html",
    redirect: "/base-fe/vue3%E7%9B%B8%E5%85%B3%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-9749c636",
    path: "/base-js/AJAX.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9749c636").then(next)
    },
  },
  {
    name: "v-f34c2576",
    path: "/base-fe/%E5%8F%8C%E5%90%91%E7%BB%91%E5%AE%9A%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f34c2576").then(next)
    },
  },
  {
    path: "/base-fe/双向绑定原理.html",
    redirect: "/base-fe/%E5%8F%8C%E5%90%91%E7%BB%91%E5%AE%9A%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/base-fe/双向绑定原理.html",
    redirect: "/base-fe/%E5%8F%8C%E5%90%91%E7%BB%91%E5%AE%9A%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-36bb1fe0",
    path: "/base-js/%E5%86%92%E6%B3%A1%E5%92%8C%E6%8D%95%E8%8E%B7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36bb1fe0").then(next)
    },
  },
  {
    path: "/base-js/冒泡和捕获.html",
    redirect: "/base-js/%E5%86%92%E6%B3%A1%E5%92%8C%E6%8D%95%E8%8E%B7.html"
  },
  {
    path: "/base-js/冒泡和捕获.html",
    redirect: "/base-js/%E5%86%92%E6%B3%A1%E5%92%8C%E6%8D%95%E8%8E%B7.html"
  },
  {
    name: "v-5e89bd58",
    path: "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e89bd58").then(next)
    },
  },
  {
    path: "/base-js/原型和原型链.html",
    redirect: "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    path: "/base-js/原型和原型链.html",
    redirect: "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    name: "v-04118d6a",
    path: "/base-js/%E5%A0%86%E5%92%8C%E6%A0%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04118d6a").then(next)
    },
  },
  {
    path: "/base-js/堆和栈.html",
    redirect: "/base-js/%E5%A0%86%E5%92%8C%E6%A0%88.html"
  },
  {
    path: "/base-js/堆和栈.html",
    redirect: "/base-js/%E5%A0%86%E5%92%8C%E6%A0%88.html"
  },
  {
    name: "v-03bab7ad",
    path: "/base-js/Promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03bab7ad").then(next)
    },
  },
  {
    name: "v-4f579701",
    path: "/base-js/%E7%BB%A7%E6%89%BF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f579701").then(next)
    },
  },
  {
    path: "/base-js/继承.html",
    redirect: "/base-js/%E7%BB%A7%E6%89%BF.html"
  },
  {
    path: "/base-js/继承.html",
    redirect: "/base-js/%E7%BB%A7%E6%89%BF.html"
  },
  {
    name: "v-4fe6db84",
    path: "/base-js/%E9%97%AD%E5%8C%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fe6db84").then(next)
    },
  },
  {
    path: "/base-js/闭包.html",
    redirect: "/base-js/%E9%97%AD%E5%8C%85.html"
  },
  {
    path: "/base-js/闭包.html",
    redirect: "/base-js/%E9%97%AD%E5%8C%85.html"
  },
  {
    name: "v-d38f7e8e",
    path: "/base-leetcode/%E4%B8%A4%E6%95%B0%E4%B9%8B%E5%92%8C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d38f7e8e").then(next)
    },
  },
  {
    path: "/base-leetcode/两数之和.html",
    redirect: "/base-leetcode/%E4%B8%A4%E6%95%B0%E4%B9%8B%E5%92%8C.html"
  },
  {
    path: "/base-leetcode/两数之和.html",
    redirect: "/base-leetcode/%E4%B8%A4%E6%95%B0%E4%B9%8B%E5%92%8C.html"
  },
  {
    name: "v-12a2da58",
    path: "/base-leetcode/%E5%88%A4%E6%96%AD%E5%AD%90%E5%BA%8F%E5%88%97.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12a2da58").then(next)
    },
  },
  {
    path: "/base-leetcode/判断子序列.html",
    redirect: "/base-leetcode/%E5%88%A4%E6%96%AD%E5%AD%90%E5%BA%8F%E5%88%97.html"
  },
  {
    path: "/base-leetcode/判断子序列.html",
    redirect: "/base-leetcode/%E5%88%A4%E6%96%AD%E5%AD%90%E5%BA%8F%E5%88%97.html"
  },
  {
    name: "v-bb6f3366",
    path: "/base-leetcode/%E5%88%A0%E9%99%A4%E6%9C%89%E5%BA%8F%E6%95%B0%E7%BB%84%E4%B8%AD%E7%9A%84%E9%87%8D%E5%A4%8D%E9%A1%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bb6f3366").then(next)
    },
  },
  {
    path: "/base-leetcode/删除有序数组中的重复项.html",
    redirect: "/base-leetcode/%E5%88%A0%E9%99%A4%E6%9C%89%E5%BA%8F%E6%95%B0%E7%BB%84%E4%B8%AD%E7%9A%84%E9%87%8D%E5%A4%8D%E9%A1%B9.html"
  },
  {
    path: "/base-leetcode/删除有序数组中的重复项.html",
    redirect: "/base-leetcode/%E5%88%A0%E9%99%A4%E6%9C%89%E5%BA%8F%E6%95%B0%E7%BB%84%E4%B8%AD%E7%9A%84%E9%87%8D%E5%A4%8D%E9%A1%B9.html"
  },
  {
    name: "v-3af47de4",
    path: "/base-leetcode/%E6%95%B0%E7%BB%84%E5%8E%BB%E9%87%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3af47de4").then(next)
    },
  },
  {
    path: "/base-leetcode/数组去重.html",
    redirect: "/base-leetcode/%E6%95%B0%E7%BB%84%E5%8E%BB%E9%87%8D.html"
  },
  {
    path: "/base-leetcode/数组去重.html",
    redirect: "/base-leetcode/%E6%95%B0%E7%BB%84%E5%8E%BB%E9%87%8D.html"
  },
  {
    name: "v-07ce21e8",
    path: "/base-leetcode/%E5%90%88%E5%B9%B6%E4%B8%A4%E4%B8%AA%E6%9C%89%E5%BA%8F%E6%95%B0%E7%BB%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07ce21e8").then(next)
    },
  },
  {
    path: "/base-leetcode/合并两个有序数组.html",
    redirect: "/base-leetcode/%E5%90%88%E5%B9%B6%E4%B8%A4%E4%B8%AA%E6%9C%89%E5%BA%8F%E6%95%B0%E7%BB%84.html"
  },
  {
    path: "/base-leetcode/合并两个有序数组.html",
    redirect: "/base-leetcode/%E5%90%88%E5%B9%B6%E4%B8%A4%E4%B8%AA%E6%9C%89%E5%BA%8F%E6%95%B0%E7%BB%84.html"
  },
  {
    name: "v-ec7b9b84",
    path: "/base-leetcode/%E6%9C%89%E6%95%88%E7%9A%84%E6%8B%AC%E5%8F%B7%E5%8C%B9%E9%85%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec7b9b84").then(next)
    },
  },
  {
    path: "/base-leetcode/有效的括号匹配.html",
    redirect: "/base-leetcode/%E6%9C%89%E6%95%88%E7%9A%84%E6%8B%AC%E5%8F%B7%E5%8C%B9%E9%85%8D.html"
  },
  {
    path: "/base-leetcode/有效的括号匹配.html",
    redirect: "/base-leetcode/%E6%9C%89%E6%95%88%E7%9A%84%E6%8B%AC%E5%8F%B7%E5%8C%B9%E9%85%8D.html"
  },
  {
    name: "v-3f399943",
    path: "/base-leetcode/%E9%95%BF%E5%BA%A6%E6%9C%80%E5%B0%8F%E7%9A%84%E5%AD%90%E6%95%B0%E7%BB%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f399943").then(next)
    },
  },
  {
    path: "/base-leetcode/长度最小的子数组.html",
    redirect: "/base-leetcode/%E9%95%BF%E5%BA%A6%E6%9C%80%E5%B0%8F%E7%9A%84%E5%AD%90%E6%95%B0%E7%BB%84.html"
  },
  {
    path: "/base-leetcode/长度最小的子数组.html",
    redirect: "/base-leetcode/%E9%95%BF%E5%BA%A6%E6%9C%80%E5%B0%8F%E7%9A%84%E5%AD%90%E6%95%B0%E7%BB%84.html"
  },
  {
    name: "v-d679ab8a",
    path: "/base-leetcode/%E9%AA%8C%E8%AF%81%E5%9B%9E%E6%96%87%E4%B8%B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d679ab8a").then(next)
    },
  },
  {
    path: "/base-leetcode/验证回文串.html",
    redirect: "/base-leetcode/%E9%AA%8C%E8%AF%81%E5%9B%9E%E6%96%87%E4%B8%B2.html"
  },
  {
    path: "/base-leetcode/验证回文串.html",
    redirect: "/base-leetcode/%E9%AA%8C%E8%AF%81%E5%9B%9E%E6%96%87%E4%B8%B2.html"
  },
  {
    name: "v-1713c856",
    path: "/base-thinking/call%E5%92%8Capply%E5%92%8Cbind%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1713c856").then(next)
    },
  },
  {
    path: "/base-thinking/call和apply和bind原理.html",
    redirect: "/base-thinking/call%E5%92%8Capply%E5%92%8Cbind%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/base-thinking/call和apply和bind原理.html",
    redirect: "/base-thinking/call%E5%92%8Capply%E5%92%8Cbind%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-5bb7fc2b",
    path: "/base-leetcode/%E7%A7%BB%E9%99%A4%E5%85%83%E7%B4%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bb7fc2b").then(next)
    },
  },
  {
    path: "/base-leetcode/移除元素.html",
    redirect: "/base-leetcode/%E7%A7%BB%E9%99%A4%E5%85%83%E7%B4%A0.html"
  },
  {
    path: "/base-leetcode/移除元素.html",
    redirect: "/base-leetcode/%E7%A7%BB%E9%99%A4%E5%85%83%E7%B4%A0.html"
  },
  {
    name: "v-640fdd97",
    path: "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-640fdd97").then(next)
    },
  },
  {
    path: "/base-thinking/new的实现.html",
    redirect: "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html"
  },
  {
    path: "/base-thinking/new的实现.html",
    redirect: "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html"
  },
  {
    name: "v-7938b4f2",
    path: "/base-thinking/%E5%87%BD%E6%95%B0%E6%9F%AF%E7%90%86%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7938b4f2").then(next)
    },
  },
  {
    path: "/base-thinking/函数柯理化.html",
    redirect: "/base-thinking/%E5%87%BD%E6%95%B0%E6%9F%AF%E7%90%86%E5%8C%96.html"
  },
  {
    path: "/base-thinking/函数柯理化.html",
    redirect: "/base-thinking/%E5%87%BD%E6%95%B0%E6%9F%AF%E7%90%86%E5%8C%96.html"
  },
  {
    name: "v-317166a2",
    path: "/base-thinking/%E5%85%B3%E4%BA%8EHTTP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-317166a2").then(next)
    },
  },
  {
    path: "/base-thinking/关于HTTP.html",
    redirect: "/base-thinking/%E5%85%B3%E4%BA%8EHTTP.html"
  },
  {
    path: "/base-thinking/关于HTTP.html",
    redirect: "/base-thinking/%E5%85%B3%E4%BA%8EHTTP.html"
  },
  {
    name: "v-74848370",
    path: "/base-thinking/%E6%B5%8F%E8%A7%88%E5%99%A8%E5%AD%98%E5%82%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74848370").then(next)
    },
  },
  {
    path: "/base-thinking/浏览器存储.html",
    redirect: "/base-thinking/%E6%B5%8F%E8%A7%88%E5%99%A8%E5%AD%98%E5%82%A8.html"
  },
  {
    path: "/base-thinking/浏览器存储.html",
    redirect: "/base-thinking/%E6%B5%8F%E8%A7%88%E5%99%A8%E5%AD%98%E5%82%A8.html"
  },
  {
    name: "v-2ad614f9",
    path: "/base-build/webpack%E7%9B%B8%E5%85%B3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ad614f9").then(next)
    },
  },
  {
    path: "/base-build/webpack相关.html",
    redirect: "/base-build/webpack%E7%9B%B8%E5%85%B3.html"
  },
  {
    path: "/base-build/webpack相关.html",
    redirect: "/base-build/webpack%E7%9B%B8%E5%85%B3.html"
  },
  {
    name: "v-ade23072",
    path: "/base-thinking/%E8%B7%AF%E7%94%B1%E5%AE%9E%E7%8E%B0%E6%9C%BA%E5%88%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ade23072").then(next)
    },
  },
  {
    path: "/base-thinking/路由实现机制.html",
    redirect: "/base-thinking/%E8%B7%AF%E7%94%B1%E5%AE%9E%E7%8E%B0%E6%9C%BA%E5%88%B6.html"
  },
  {
    path: "/base-thinking/路由实现机制.html",
    redirect: "/base-thinking/%E8%B7%AF%E7%94%B1%E5%AE%9E%E7%8E%B0%E6%9C%BA%E5%88%B6.html"
  },
  {
    name: "v-ee2b0b78",
    path: "/base-thinking/%E6%B7%B1%E6%8B%B7%E8%B4%9D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ee2b0b78").then(next)
    },
  },
  {
    path: "/base-thinking/深拷贝.html",
    redirect: "/base-thinking/%E6%B7%B1%E6%8B%B7%E8%B4%9D.html"
  },
  {
    path: "/base-thinking/深拷贝.html",
    redirect: "/base-thinking/%E6%B7%B1%E6%8B%B7%E8%B4%9D.html"
  },
  {
    name: "v-527c5581",
    path: "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-527c5581").then(next)
    },
  },
  {
    path: "/base-thinking/尾调用优化.html",
    redirect: "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html"
  },
  {
    path: "/base-thinking/尾调用优化.html",
    redirect: "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html"
  },
  {
    name: "v-6fdfaf23",
    path: "/base-thinking/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F%E5%92%8C%E5%8F%91%E5%B8%83%E8%AE%A2%E9%98%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fdfaf23").then(next)
    },
  },
  {
    path: "/base-thinking/观察者模式和发布订阅.html",
    redirect: "/base-thinking/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F%E5%92%8C%E5%8F%91%E5%B8%83%E8%AE%A2%E9%98%85.html"
  },
  {
    path: "/base-thinking/观察者模式和发布订阅.html",
    redirect: "/base-thinking/%E8%A7%82%E5%AF%9F%E8%80%85%E6%A8%A1%E5%BC%8F%E5%92%8C%E5%8F%91%E5%B8%83%E8%AE%A2%E9%98%85.html"
  },
  {
    name: "v-89a83a96",
    path: "/config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89a83a96").then(next)
    },
  },
  {
    name: "v-b74cc05e",
    path: "/base-utils/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b74cc05e").then(next)
    },
  },
  {
    path: "/base-utils/正则表达式.html",
    redirect: "/base-utils/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    path: "/base-utils/正则表达式.html",
    redirect: "/base-utils/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    name: "v-00b71e8c",
    path: "/base-utils/%E9%98%B2%E6%8A%96%E5%92%8C%E8%8A%82%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00b71e8c").then(next)
    },
  },
  {
    path: "/base-utils/防抖和节流.html",
    redirect: "/base-utils/%E9%98%B2%E6%8A%96%E5%92%8C%E8%8A%82%E6%B5%81.html"
  },
  {
    path: "/base-utils/防抖和节流.html",
    redirect: "/base-utils/%E9%98%B2%E6%8A%96%E5%92%8C%E8%8A%82%E6%B5%81.html"
  },
  {
    name: "v-dd05e5c2",
    path: "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dd05e5c2").then(next)
    },
  },
  {
    path: "/base-utils/扁平数组转化成tree.html",
    redirect: "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html"
  },
  {
    path: "/base-utils/扁平数组转化成tree.html",
    redirect: "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]