/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/zhongjiawei/Desktop/hard-learn/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-640fdd97",
    path: "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-640fdd97").then(next)
    },
  },
  {
    path: "/base-thinking/new的实现.html",
    redirect: "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html"
  },
  {
    path: "/base-thinking/new的实现.html",
    redirect: "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html"
  },
  {
    name: "v-5e89bd58",
    path: "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e89bd58").then(next)
    },
  },
  {
    path: "/base-js/原型和原型链.html",
    redirect: "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    path: "/base-js/原型和原型链.html",
    redirect: "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    name: "v-7d3afeea",
    path: "/base-css/BFC.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d3afeea").then(next)
    },
  },
  {
    name: "v-89a83a96",
    path: "/config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89a83a96").then(next)
    },
  },
  {
    name: "v-dd05e5c2",
    path: "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dd05e5c2").then(next)
    },
  },
  {
    path: "/base-utils/扁平数组转化成tree.html",
    redirect: "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html"
  },
  {
    path: "/base-utils/扁平数组转化成tree.html",
    redirect: "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html"
  },
  {
    name: "v-527c5581",
    path: "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-527c5581").then(next)
    },
  },
  {
    path: "/base-thinking/尾调用优化.html",
    redirect: "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html"
  },
  {
    path: "/base-thinking/尾调用优化.html",
    redirect: "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html"
  },
  {
    name: "v-5d8a074e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d8a074e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]