/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Jovi's Blob",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "实现new关键字",
      "frontmatter": {},
      "regularPath": "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html",
      "relativePath": "base-thinking/new的实现.md",
      "key": "v-640fdd97",
      "path": "/base-thinking/new%E7%9A%84%E5%AE%9E%E7%8E%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "实现new关键字",
          "slug": "实现new关键字"
        },
        {
          "level": 3,
          "title": "new 关键词的作用",
          "slug": "new-关键词的作用"
        }
      ]
    },
    {
      "title": "原型和原型链",
      "frontmatter": {},
      "regularPath": "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
      "relativePath": "base-js/原型和原型链.md",
      "key": "v-5e89bd58",
      "path": "/base-js/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
      "headers": [
        {
          "level": 2,
          "title": "原型和原型链",
          "slug": "原型和原型链"
        },
        {
          "level": 3,
          "title": "函数对象 和 普通对象",
          "slug": "函数对象-和-普通对象"
        },
        {
          "level": 3,
          "title": "prototype 和 _proto_",
          "slug": "prototype-和-proto"
        },
        {
          "level": 3,
          "title": "原型链",
          "slug": "原型链"
        }
      ]
    },
    {
      "title": "什么是BFC?",
      "frontmatter": {},
      "regularPath": "/base-css/BFC.html",
      "relativePath": "base-css/BFC.md",
      "key": "v-7d3afeea",
      "path": "/base-css/BFC.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是BFC?",
          "slug": "什么是bfc"
        },
        {
          "level": 3,
          "title": "首先理解BFC概念",
          "slug": "首先理解bfc概念"
        },
        {
          "level": 3,
          "title": "触发条件",
          "slug": "触发条件"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-89a83a96",
      "path": "/config.html"
    },
    {
      "title": "扁平化数组转化成tree",
      "frontmatter": {},
      "regularPath": "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html",
      "relativePath": "base-utils/扁平数组转化成tree.md",
      "key": "v-dd05e5c2",
      "path": "/base-utils/%E6%89%81%E5%B9%B3%E6%95%B0%E7%BB%84%E8%BD%AC%E5%8C%96%E6%88%90tree.html",
      "headers": [
        {
          "level": 2,
          "title": "扁平化数组转化成tree",
          "slug": "扁平化数组转化成tree"
        },
        {
          "level": 3,
          "title": "方法1，不考虑性能，直接递归",
          "slug": "方法1-不考虑性能-直接递归"
        },
        {
          "level": 3,
          "title": "方法2，优化性能",
          "slug": "方法2-优化性能"
        }
      ]
    },
    {
      "title": "什么是尾调用？",
      "frontmatter": {},
      "regularPath": "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html",
      "relativePath": "base-thinking/尾调用优化.md",
      "key": "v-527c5581",
      "path": "/base-thinking/%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是尾调用？",
          "slug": "什么是尾调用"
        },
        {
          "level": 3,
          "title": "概念理解",
          "slug": "概念理解"
        },
        {
          "level": 3,
          "title": "尾调用优化",
          "slug": "尾调用优化"
        },
        {
          "level": 3,
          "title": "尾递归",
          "slug": "尾递归"
        },
        {
          "level": 3,
          "title": "递归函数优化",
          "slug": "递归函数优化"
        }
      ]
    },
    {
      "title": "hard-learn",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5d8a074e",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "关于",
        "link": "/about"
      },
      {
        "text": "友链",
        "link": "/b"
      },
      {
        "text": "下拉菜单",
        "ariaLabel": "这是提示语",
        "items": [
          {
            "text": "todo",
            "link": "/",
            "target": "_self"
          },
          {
            "text": "todo",
            "link": "/",
            "target": "_blank"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "Javascript基础",
        "path": "",
        "collapsable": true,
        "sidebarDepth": -1,
        "children": [
          {
            "title": "原型和原型链",
            "path": "/base-js/原型和原型链"
          }
        ]
      },
      {
        "title": "CSS基础",
        "path": "",
        "collapsable": true,
        "sidebarDepth": -1,
        "children": [
          {
            "title": "什么是BFC",
            "path": "/base-css/BFC"
          }
        ]
      },
      {
        "title": "工具方法",
        "path": "",
        "sidebarDepth": -1,
        "children": [
          {
            "title": "扁平数组转化成tree",
            "path": "/base-utils/扁平数组转化成tree"
          }
        ]
      },
      {
        "title": "一点儿思考",
        "path": "",
        "sidebarDepth": -1,
        "children": [
          {
            "title": "尾调用优化",
            "path": "/base-thinking/尾调用优化"
          },
          {
            "title": "new的实现",
            "path": "/base-thinking/new的实现"
          }
        ]
      }
    ]
  }
}